import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../styles/global.css'
import { LayoutHandlerWrapper } from "@/utils/layouthandler";
import Footer from "@/components/Footer/footer";
import Icon from '../../public/assets/images/logo-primary.svg'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cliff Barnes Bränneri",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head><link rel="icon" href={Icon.src} sizes="any" /></head>
      <LayoutHandlerWrapper>
        <body>
          {/* <Header /> */}
          <main>
            {children}
          </main>
          <Footer />
        </body>
      </LayoutHandlerWrapper>
    </html>
  );
}
